name: feedback
description: A Flutter package for getting better feedback. It allows the user to give interactive feedback directly in the app.
version: 0.4.0
author: Jonas Uekötter
homepage: https://uekoetter.dev
repository: https://github.com/ueman/feedback
issue_tracker: https://github.com/ueman/feedback/issues

environment:
  sdk: '>=2.2.2 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ">=0.11.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: