name: supernodeapp
description: Mobile app used to interact with MXC Supernodes.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.2

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  # https://pub.dev/packages/device_info
  device_info: ^0.4.2+4
  # https://pub.dev/packages/geolocator
  geolocator: ^6.0.0+4
  # https://pub.dev/packages/flutter_appcenter
  flutter_appcenter: ^1.0.10
  # https://pub.dev/packages/fl_chart
  fl_chart: ^0.10.1
  # https://pub.dev/packages/charts_flutter
  charts_flutter: ^0.9.0
  # https://pub.dev/packages/webview_flutter
  webview_flutter: ^0.3.22+1
  # https://pub.dev/packages/modal_bottom_sheet
  modal_bottom_sheet: 0.2.0
  #https://pub.dev/packages/solid_bottom_sheet
  solid_bottom_sheet: ^0.1.9
  # https://pub.dev/packages/dio
  dio: ^3.0.9
  # https://pub.dev/packages/flutter_i18n
  flutter_i18n: ^0.13.0
  # https://pub.dev/packages/flutter_local_notifications
  flutter_local_notifications: ^1.4.1
  # https://pub.dev/packages/mapbox_gl
  mapbox_gl: ^0.8.0
  # https://pub.dev/packages/fish_redux
  fish_redux: ^0.3.1
  # https://pub.dev/packages/latlong
  latlong: ^0.6.1
  # https://pub.dev/packages/majascan
  majascan: ^0.3.7
  # https://pub.dev/packages/package_info
  package_info: ^0.4.1
  # https://pub.dev/packages/permission_handler
  permission_handler: ^5.0.1+1
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^0.5.6+3
  # https://pub.dev/packages/shimmer
  shimmer: ^1.1.1
  # https://pub.dev/packages/sqflite
  sqflite: ^1.3.0
  # https://pub.dev/packages/supernova_flutter_ui_toolkit
  supernova_flutter_ui_toolkit: ^0.0.2
  # https://pub.dev/packages/qr_flutter
  qr_flutter: ^3.2.0
  # https://pub.dev/packages/url_launcher
  url_launcher: ^5.4.5
  # https://pub.dev/packages/toast
  toast: ^0.1.5
  # https://pub.dev/packages/flutter_spinkit
  flutter_spinkit: '^2.1.0'
  # https://pub.dev/packages/localstorage
  localstorage: ^3.0.0
  # https://pub.dev/packages/local_auth
  # temporary using 3rd party branch
  # return back after merged - https://github.com/flutter/plugins/pull/2760
  local_auth: ^0.6.3
  # https://pub.dev/packages/location
  location: ^3.0.0
  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^2.2.0+1
  # https://pub.dev/packages/connectivity
  connectivity: ^0.4.8+6
  # https://pub.dev/packages/json_serializable
  json_serializable: ^3.3.0
  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^8.8.1
  # https://pub.dev/packages/ethereum_address
  ethereum_address: ^1.0.1
  # https://pub.dev/packages/decimal
  decimal: ^0.3.5
  # https://pub.dev/packages/share
  share: ^0.6.5
  # https://pub.dev/packages/path_provider
  path_provider: 1.6.14
  # https://pub.dev/packages/pagination_view
  pagination_view: ^1.0.3+2
  native_screenshot: 
    path: packages/native_screenshot
  # https://pub.dev/packages/feedback
  feedback:
    path: packages/feedback
  flutter_mapbox_native:
    path: packages/flutter_mapbox_native
  dotenv: ^2.0.0

dependency_overrides:
  local_auth:
    path: packages/local_auth
    
dev_dependencies:
  json_annotation: ^3.0.0
  build_runner: ^1.8.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/flutter_i18n/
    # - assets/flutter_i18n/en/
    # - assets/flutter_i18n/zh_CN/
    # - assets/flutter_i18n/zh_TW/
    # - assets/flutter_i18n/ko/
    # - assets/flutter_i18n/ja/
    - assets/images/app/
    - assets/images/login/
    - assets/images/splash/
    - assets/images/home/
    - assets/images/deposit/
    - assets/images/withdraw/
    - assets/images/stake/
    - assets/images/device/
    - assets/images/calculator/currencies/
    - assets/images/connectivity/
    - assets/images/settings/
    - assets/images/maintenance/
    - assets/others/
    - assets/js/

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: .SF NS Display
      fonts:
        - asset: assets/fonts/SFNSDisplay.ttf
    - family: .SF NS Text
      fonts:
        - asset: assets/fonts/SFNSText.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
