name: Build APK

on: [push]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setting up Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Setting up subosito/flutter-action@v1
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.20'
    - name: Cleaning workspace
      run: flutter clean
    - name: Install NDK (workaround to https://github.com/gradle/gradle/issues/12440)
      run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}
    - name: Building the APK
      run: flutter build apk --flavor prod
      env:
        APPCENTER_BUILD_ID: ${{ secrets.APPCENTER_BUILD_ID}}
        APPCENTER_KEYSTORE_PASSWORD: ${{ secrets.APPCENTER_KEYSTORE_PASSWORD}}
        APPCENTER_KEY_ALIAS: ${{ secrets.APPCENTER_KEY_ALIAS}}
        APPCENTER_KEY_PASSWORD: ${{ secrets.APPCENTER_KEY_PASSWORD}}
