name: Build APK

on: [push]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set env
      run: echo ::set-env name=APPCENTER_BUILD_ID::$(echo $GITHUB_RUN_NUMBER)
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.20'
    - run: flutter pub get
    - name: Install NDK as workaround https://github.com/gradle/gradle/issues/12440
      run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}
    - run: flutter build apk --flavor prod
