name: flutter pipeline
on:
  pull_request:

jobs:
  drive_ios:
    name: Drive flutter (IOS)
    strategy:
      matrix:
        device:
        - "iPhone SE (2nd generation) (14.1)"
        - "iPhone 11 Pro Max (14.1)"
      fail-fast: false
    runs-on: self-hosted
    steps:
    - name: "List all simulators"
      run: "xcrun instruments -s"
    - name: "Start Simulator"
      run: |
        UDID=$(
          xcrun instruments -s |
          awk \
            -F ' *[][]' \
            -v 'device=${{ matrix.device }}' \
            '$1 == device { print $2 }'
        )
        xcrun simctl boot "${UDID:?No Simulator with this name found}"
      continue-on-error: true
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup subosito/flutter-action@v1
      uses: subosito/flutter-action@v1
      with:
        channel: beta
    - name: Clean workspace
      run: flutter clean
    - name: Upgrade flutter
      run: flutter upgrade
    - name: create env file
      run: |
        touch assets/.env
    - name: "Run Flutter Driver tests"
      run: "flutter drive --target=test_driver/app.dart"
      env:
        TESTING_USER: ${{ secrets.TESTING_USER }}
        TESTING_PASSWORD: ${{ secrets.TESTING_PASSWORD }}

  build_ios:
    name: Build flutter (IOS)
    needs: drive_ios
    runs-on: self-hosted
    steps:
    - name: Trigger build thru appcenter API
      run: 'curl -X POST "https://api.appcenter.ms/v0.1/apps/MXC-Foundation-gGmbH/DataDashIOS/branches/jeff%2FMMD-97%2FreTest/builds" -H  "accept: application/json" -H  "X-API-Token: ${{ secrets.APPCENTER_DATADASH_IOS }}" -H  "Content-Type: application/json" -d "{}"'